name: Example Workflow
on: [push]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Output
        run: |
          echo "my_output=Hello, world!" >> $GITHUB_ENV
      - name: Print Output
        run: |
          echo "Output is ${{ env.my_output }}"
